controller_manager:
  ros__parameters:
    update_rate: 10 
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: TrxJointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50
    command_interfaces:
      - position

    state_interfaces:
      - position
